apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: my-node-app  # Example Jenkins build number
        imagePullPolicy: Never  # Ensures Kubernetes uses the locally built image
        ports:
        - containerPort: 3000