apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-shopping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-shopping
  template:
    metadata:
      labels:
        app: nodejs-shopping
    spec:
      containers:
      - name: nodejs-shopping
        image: nodejs-shopping  # Example Jenkins build number
        imagePullPolicy: Never  # Ensures Kubernetes uses the locally built image
        ports:
        - containerPort: 3000
