apiVersion: v1
kind: Service
metadata:
  name: nodejs-shopping-service
spec:
  selector:
    app: nodejs-shopping
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
